import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/Provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html data-theme="corporate" lang="en">
      <body className={`${inter.className} min-h-screen bg-white text-black`}>
          <NextAuthProvider>
              {children}
          </NextAuthProvider>
        </body>
    </html>
  );
}
