import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Nav/Navbar";
import { headers } from "next/headers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headersList = headers();
  const pathname = headersList.get('x-pathname')|| ''
  const noNavRoutes = ['/', '/register'];

  return (
    <html data-theme="corporate" lang="en">
      <body className={`${inter.className} min-h-screen bg-white text-black`}>
      {!noNavRoutes.includes(pathname) && 
      <Navbar/>}  
        {children}
        </body>
    </html>
  );
}
